[package]
name = "schemer-repl"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0"
isatty = "0.1"
log = "0.4"
pretty_env_logger = "0.4"
rustyline = "9.0"
search_path = "0.1"
schemer-parse = { version = "0.1", path = "../schemer-parse" }
schemer-lang = { version = "0.1", path = "../schemer-lang" }
schemer-library = { version = "0.1", path = "../schemer-library" }
structopt = "0.3"
xdirs = "0.1"
