[package]
name = "schemer-lang"
version = "0.1.0"
edition = "2018"

[features]
default = []
char-names = ["unicode_names2"]

[dependencies]
lazy_static = "1.4"
num = "0.4"
paste = "1.0"
rust_decimal = "1.15"
unique_id = "0.1"

unicode_names2 = { version = "0.4", optional = true }
